FROM python:3.10.12

COPY . /app/src_models
WORKDIR /app/
RUN python3 -m venv venv && . venv/bin/activate
RUN  apt update && apt install libgl1-mesa-glx -y
RUN pip3 install -r src_models/req.txt

CMD [ "uvicorn", "src_models.main:app", "--reload", "--host", "0.0.0.0", "--port", "5000" ]

