version: '3'

services:
  web:
    build:
     context: .
    depends_on:
      - model
      - db
    ports:
      - '8000:8000'
    networks:
      - app-network
    volumes:
      - images:/mnt/images
    env_file: '.env'
    
  model:
    build:
      dockerfile: Dockerfile.model
      context: src_models
    networks:
      - app-network

  db:
    image: postgres:17-bullseye
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app-db
    volumes:
      - flask-app-data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  images:
  flask-app-data:
    external: true
networks:
  app-network:
  