- name: Deploy Docker Compose stack
  hosts: ec2
  become: true
  tasks:

    - name: Install required packages
      dnf:
        name:
        - git
        - git-lfs
        - docker
        state: present
        update_cache: yes

    - name: Install Docker Compose plugin
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Clone Repository
      git:
        repo: "https://github.com/mporada259449/face-app"
        dest: /home/{{ ansible_user }}/face-app
        version: master

    - name: Download model
      shell: git-lfs pull
      args:
        chdir: /home/{{ ansible_user }}/face-app

    - name: Create database
      shell: bash scripts/create-db.sh
      args:
        chdir: /home/{{ ansible_user }}/face-app
    
    - name: Create Stack
      shell: bash scripts/deploy-services.sh
      args:
        chdir: /home/{{ ansible_user }}/face-app
